atobm: close memory leaks
Fix leaks reported by Oracle Parfait (though they don't last long,
since the program exits immediately after leaking):

Error: Memory leak
   Memory leak [memory-leak] (CWE 401):
      Memory leak of pointer pointer allocated with _new_scan_list(bytes_per_scanline)
        at line 260 of atobm.c in function 'doit'.
        calloc called at line 180 in function '_new_scan_list'
        Allocated value returned to caller at line 193
          pointer allocated at line 250 in function 'doit' with _new_scan_list(bytes_per_scanline)
          pointer leaks when (i + 1) >= <unknown> at line 275
              and buf[0] != 0 at line 225.

Error: Memory leak
   Memory leak [memory-leak] (CWE 401):
      Memory leak of pointer pointer allocated with _new_scan_list(bytes_per_scanline)
        at line 316 of atobm.c in function 'doit'.
        calloc called at line 180 in function '_new_scan_list'
        Allocated value returned to caller at line 193
          pointer allocated at line 250 in function 'doit' with _new_scan_list(bytes_per_scanline)
          pointer leaks when slist != NULL at line 252
              and (i + 1) >= <unknown> at line 275
              and (i + 1) >= <unknown> at line 303.

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>