Stop memory leaks from XtNewString(StripFilename(filename))
StripFilename() already allocates a new string for its result,
we don't need to duplicate it and then lose the pointer to the
first one.

Fixes errors found by Oracle Parfait 1.5.1 bug checking tool:

Error: Memory leak (CWE 401)
   Memory leak of pointer pointer allocated with StripFilename(filename)
        at line 1119 of Bitmap.c in function 'BWReadFile'.
          pointer allocated at line 1106 with StripFilename(filename).
          pointer leaks when StripFilename(filename) != NULL at line 1106.
Error: Memory leak (CWE 401)
   Memory leak of pointer pointer allocated with StripFilename(filename)
        at line 1119 of Bitmap.c in function 'BWReadFile'.
          pointer allocated at line 1106 with StripFilename(filename).

Error: Memory leak (CWE 401)
   Memory leak of pointer pointer allocated with StripFilename(filename)
        at line 1222 of Bitmap.c in function 'BWWriteFile'.
          pointer allocated at line 1202 with StripFilename(filename).
          pointer leaks when StripFilename(filename) != NULL at line 1202.
Error: Memory leak (CWE 401)
   Memory leak of pointer pointer allocated with StripFilename(filename)
        at line 1222 of Bitmap.c in function 'BWWriteFile'.
          pointer allocated at line 1202 with StripFilename(filename).

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>