Stop memory leak in XmuWriteBitmapDataToFile()
StripFilename() allocates a new string for its result, so after we're
done with it, free it instead of just losing the pointer to it.

Fixes errors found by Oracle Parfait 1.5.1 bug checking tool:

Error: Memory leak (CWE 401)
   Memory leak of pointer basename allocated with StripFilename(filename)
        at line 712 of Bitmap.c in function 'XmuWriteBitmapDataToFile'.
          basename allocated at line 691 with StripFilename(filename).
          basename leaks when i >= data_length at line 702.
Error: Memory leak (CWE 401)
   Memory leak of pointer basename allocated with StripFilename(filename)
        at line 715 of Bitmap.c in function 'XmuWriteBitmapDataToFile'.
          basename allocated at line 691 with StripFilename(filename).

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>